### ISSUE TITLE
rebrand to npme

### ISSUE THREAD

**Issue by bcoe** [npm/npmo-docs#4]
We should rebrand this to npm Enterprise before we officially launch, a hassle I know.

**Comment by ashleygwilliams** [comment]
agreed. already have it at the back of my mind. thanks for filing!

**Comment by kevinSuttle** [comment]
PR opened: https://github.com/npm/npmo-docs/pull/7

**Comment by ashleygwilliams** [comment]
partially solved by #7, now we just need to replace npmO with npmE
